### ISSUE TITLE
ES 5 Compatibility

### ISSUE THREAD

**Issue by alextudose** [BrianDGLS/hypo-container#4]
Hello,
hypo-container doesn't work for IE11.
Can ES5 compatibility be added?
Thank you :)

**Comment by BrianDGLS** [comment]
Sure, will update soon. Happy to accept Pull Requests.

**Comment by BrianDGLS** [comment]
@alextudose Version 1.0.9 is now compiled to es5.

```npm install --save hypo-container@1.0.9```

Let me know if any issues.

Thanks.

**Comment by alextudose** [comment]
It's all good, thank you :+1:
