### ISSUE TITLE
simple service assignments

### ISSUE THREAD

**Issue by nicuvlad7** [BrianDGLS/hypo-container#5]
Quick question: if you have a service like :

.register('owner', c => new Person('Brian', 26));

why not use : 

.register('owner', () => new Person('Brian', 26));

since you might never use that instance. I'd like to know if one of the 2 is better in terms of memory maybe.

**Comment by BrianDGLS** [comment]
Hi @nicuvlad7 ,

In this instance you may use either or.

I am passing in the `c` here as an example, to show users that the container instance is available when registering a service.

Thanks.
